Creator "Cayley"
graph [ directed 1
	node [ id 0 label "_:n7436119166394495939" ]
	node [ id 1 label "<foaf:Person>" ]
	edge [ source 0 target 1 label "<rdf:type>" ]
	node [ id 2 label "&quot;Luke&quot;" ]
	edge [ source 0 target 2 label "<foaf:givenName>" ]
	node [ id 3 label "&quot;Skywalker&quot;" ]
	edge [ source 0 target 3 label "<foaf:familyName>" ]
	node [ id 4 label "&quot;23&quot;^^<xsd:integer>" ]
	edge [ source 0 target 4 label "<foaf:age>" ]
	node [ id 5 label "_:n5283327168633809195" ]
	edge [ source 5 target 1 label "<rdf:type>" ]
	edge [ source 5 target 0 label "<foaf:knows>" ]
	node [ id 6 label "&quot;Leia&quot;" ]
	edge [ source 5 target 6 label "<foaf:givenName>" ]
	node [ id 7 label "&quot;Organa&quot;" ]
	edge [ source 5 target 7 label "<foaf:familyName>" ]
]
