# https://taskfile.dev

version: '2'

vars:
  APPNAME: cayley-cookbook

tasks:
  default:
    desc: Executes all the tests then build the binary.
    cmds:
      - task: build_website

  build_website:
    desc: Build the static website content
    cmds:
      - cd website
      - hugo -D

